Sprint1
maxsmith1984/BeautyWorld pull request #1
Opened 2023-03-23 10:57 UTC by maxsmith1984

2023-03-29 15:07 UTC, euge-huge requested changes
Работу посмотрел!
Отличная, почти идеальная даже, пришлось искать, что можно улучшить))!
Так держать, начало замечательное, надеюсь, дальше будет только лучше)

2023-03-29 15:07 UTC, euge-huge commented on index.html
> +                    <a class="header__title" href="/">Мир Красоты</a>
`стиль кода` `можно лучше`

Обычно не принято разделять начало блока пустой строкой, а вот делать пустые строки между блоками, которые сливаются - хороший тон.

Например:
```
<div class="block">
  <div class="title"></div>

  <img>

  <div class="description></div>
</div>
```

Но не нужно этим злоупотреблять =)
Например элементы, которые являются очень подобными друг другу, лучше оставлять друг за другом, списки, ссылки и тд

Например 
```
<ul class="list">
  <li></li>
  <li></li>
  <li></li>
</ul>
```

2023-03-29 15:07 UTC, euge-huge commented on index.html
> +                            </li>
`нужно поправить`

Элементы навигации можно отнести к элементам, количество которых может возрасти. Пока это выглядит так:

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/58856916/227944804-e9a312de-046a-4d82-a9c8-709a9cf7066e.png">

Хочется увидеть, что-то более дружелюбное =)

Фиксировать размеры, не нужно.
Могут пригодиться свойства:
```
min-width: fit-content;
flex-wrap: wrap;
flex-grow: ...;
gap: ...px ...px;
```

2023-03-29 15:07 UTC, euge-huge commented on style.css
> +}
`отлично`

Маленькая деталь, а глаз радует =)

2023-03-29 15:07 UTC, euge-huge commented on style.css
> +    z-index: 1;
`можно лучше`

Если я захочу вставить другую картинку, то увижу следующее:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/58856916/228555104-302d2dbf-5a1b-4ddf-b6e3-0c50d7ea5dc0.png">
Так как картинка ничем не ограничена!

Попробуй сделать так, чтобы при любом изображении все выглядело хорошо)

2023-03-29 15:07 UTC, euge-huge commented on index.html
> +                </div>
`нужно поправить`

Если я попытаюсь увеличить описание выше, то контейнер с видео примет такой вид:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/58856916/228556421-2bdd437f-4a70-4703-85cb-c998f2bc38cf.png">

Попробуй сделать так, чтобы все оставалось на своих местах)

Здесь же можно доработать блок с изображением, чтобы можно было подставить любое изображение и это не сдвигало блок рядом с описанием и всегда имело круглые края (даже если изображение с углами).
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/58856916/228575764-c1b28b61-fd53-4ef7-8236-a22c67a76fc5.png">

2023-03-29 15:07 UTC, euge-huge commented on index.html
> +
`отлично`

Тут все отлично и с переполнением, и если я добавлю новые блоки, они пойдут в следующую строку, круто! =)

2023-03-29 15:07 UTC, euge-huge commented on index.html
> +                            </li>
`нужно поправить`

Нужно попробовать доработать переполнение тоже:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/58856916/228577290-73c559a6-7571-4147-81cc-bd9de96d930d.png">

А то вылазит за пределы контейнера)

2023-03-29 15:07 UTC, euge-huge commented on style.css
`можно лучше`

Я бы вынес в папку styles этот файл.

Для лендингов часто принятая структура:
| public
|--> index.html
|--> styles
|      |--> main.css
|      |--> other.css
|--> scripts
|      |--> index.js
|      |--> other.js
|--> fonts
|      |--> ...

и так далее)

2023-03-29 15:07 UTC, euge-huge commented on style.css
> +
`можно лучше`

body лучше рядом с html

2023-03-29 15:07 UTC, euge-huge commented on style.css
> +}
`можно лучше`

`a` тоже лучше h1,h2 и другим общим для всей страницы элементам (то есть выше)

2023-03-29 15:07 UTC, euge-huge commented on style.css
> +}
`можно лучше`

Можно убрать отступы у самих айтемов и добавить свойство `gap: 0px 28px;` у **.navigation__list**

2023-03-29 15:07 UTC, euge-huge commented on style.css
`если интересно`

Можно посмотреть стайл гайд здесь:
https://learn.javascript.ru/css-format

Более полезно обратить на порядок стилей в этом гайде (вырезка ниже):

Рекомендуется располагать свойства в следующем порядке:
Сначала положение элемента относительно других: position, left/right/top/bottom, float, clear, z-index.
Затем размеры и отступы: width, height, margin, padding…
Рамка border, она частично относится к размерам.
Общее оформление содержимого: list-style-type, overflow…
Цветовое и стилевое оформление: background, color, font…

2023-03-29 15:54 UTC, maksim-salchak commented on index.html
> +                    <a class="header__title" href="/">Мир Красоты</a>
Поправил

2023-03-29 15:55 UTC, maxsmith1984 commented on index.html
> +                            </li>
Да, обратил внимание позже. Поправил уже, заадаптировал)

2023-03-29 15:56 UTC, maxsmith1984 commented on style.css
> +}
Спасибо)

2023-03-29 16:02 UTC, maxsmith1984 commented on style.css
> +    z-index: 1;
Ограничил width картинки 524px

2023-03-29 16:04 UTC, maxsmith1984 commented on style.css
> +}
Их вообще убрал. Подключил reset.css вместо normalize, т.к. там больше обнуляющих свойств.

2023-03-29 16:07 UTC, maxsmith1984 commented on style.css
> +}
В уроке Константин использовал данную работу с псевдоэлементами, поэтому решил попробовать)
Убрал, сделал gap)

2023-03-29 16:08 UTC, maxsmith1984 commented on style.css
Спасибо! Отредактирую

2023-03-29 16:11 UTC, maxsmith1984 commented on style.css
Хорошо
Я сильно на структуру не обращал внимания, ибо дальше будем подключать gulp и реструктуризация. Уже подключил и переделал

2023-03-29 16:17 UTC, maxsmith1984 commented on index.html
> +                            </li>
Поправил. Еще поправить, чтобы соседние блоки не сжимался контент от переполнения

2023-03-30 15:47 UTC, euge-huge approved these changes

2023-03-31 04:19 UTC, merged